config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  root 'summary#index' 


  get 'home/login'
  get 'home/index'
  get 'home/home'
  get 'home/clear_employee'
  post 'home/time_in_user'
  post 'home/validate_login'

  get 'admin', to: "dashboard#index"
  get 'login', to: "access#login"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'dashboard/index'
  get 'css_sample/index'
  get 'css_sample/home'

  resources :deduction_details
  resources :deductions
  resources :salaries
  resources :leave_details
  resources :leaves
  resources :day_types
  resources :attendances
  resources :departments
  resources :admin_users
  resources :salary_types
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  belongs_to :day_type_name, foreign_key: "day_type", class_name: "DayType"

  scope :attendance_by_date, -> (id) {where(day_type: id)}
  
end

app/models/day_type.rb
class DayType < ApplicationRecord
  belongs_to :employee, foreign_key: 'user_id'
  has_many :attendances, foreign_key: 'day_type'
  
  scope :sorted, -> {order(id: :desc)}

  private
    
end

app/models/deduction.rb
class Deduction < ApplicationRecord
  belongs_to :deduction_detail, foreign_key: "deduction_id"
  belongs_to :salary
end

app/models/deduction_detail.rb
class DeductionDetail < ApplicationRecord
  has_many :deduction
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :employee, foreign_key: 'manager'
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one_attached :image
  belongs_to :salary_type
  belongs_to :department
  has_many :departments
  has_many :attendances
  has_many :day_types
  has_many :leaves
  has_many :salaries
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :employee
  belongs_to :leave_detail, foreign_key: "leave_details_id"
end

app/models/leave_detail.rb
class LeaveDetail < ApplicationRecord
  has_many :leaves, class_name: :Leave, foreign_key: "leave_details_id"
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee
  has_many :deduction
end

app/models/salary_type.rb
class SalaryType < ApplicationRecord
  has_many :employees
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :set_fields, only: [:new, :edit, :update, :create]
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name,:image, :address, :gender, :contact_no, :email, :position, :image, :rfid_code, :hire_date, :salary_type_id, :department_id)
    end

    def set_fields
      @departments = Department.all
      @salaries = SalaryType.all
    end
    
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/css_sample_helper.rb
module CssSampleHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/day_types_helper.rb
module DayTypesHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/employees/_form.html.erb
<div class="jumbotron form-center">
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control"  %>
  </div>

 <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :gender %>
        <%= form.text_field :gender, class: "form-control"  %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :contact_no %>
        <%= form.text_field :contact_no, class: "form-control"  %>
      </div>  
    </div>
  </div> 

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control"  %>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :position %>
        <%= form.text_field :position, class: "form-control"  %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :rfid_code %>
        <%= form.text_field :rfid_code, class: "form-control"  %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :hire_date %>
    <%= form.date_field :hire_date, class: "form-control" %>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :salary_type_id %>
        <%= form.select :salary_type_id, @salaries.map{ |s| [s.name, s.id]}, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :department_id %>
        <%= form.select :department_id, @departments.map{ |d| [d.name, d.id]}, {}, {class: "form-control"} %>
      </div>    
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>
<hr>
<div class="jumbotron">
<table class="model-information">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Contact no</th>
      <th>Position</th>
      <th>Salary type</th>
      <th>Department</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.gender %></td>
        <td><%= employee.contact_no %></td>
        <td><%= employee.position %></td>
        <td><%= link_to employee.salary_type.name, salary_type_path(employee.salary_type) %></td>
        <td><%= link_to employee.department.name, department_path(employee.department) %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path, class: "btn btn-primary margin-normal"  %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
  <div class="show-details">
  <p id="notice"><%= notice %></p>
  <h1><%= @employee.name %></h1><hr>


  <% if @employee.image.attachment.present? %>
      <%= image_tag(@employee.image) %>
  <% end %>

  <p>
    <strong>Address:</strong>
    <%= @employee.address %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @employee.gender %>
  </p>

  <p>
    <strong>Contact no:</strong>
    <%= @employee.contact_no %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @employee.email %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= @employee.position %>
  </p>


  <p>
    <strong>Rfid code:</strong>
    <%= @employee.rfid_code %>
  </p>

  <p>
    <strong>Hire date:</strong>
    <%= @employee.hire_date %>
  </p>

  <p>
    <strong>Salary type:</strong>
    <%= link_to @employee.salary_type.name, salary_type_path(@employee.salary_type) %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= link_to @employee.department.name, department_path(@employee.department) %>
  </p>

  <%= link_to 'Edit', edit_employee_path(@employee) %> |
  <%= link_to 'Back', employees_path %>
</div>