config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  root 'summary#index' 


  get 'home/login'
  get 'home/index'
  get 'home/home'
  get 'home/clear_employee'
  post 'home/time_in_user'
  post 'home/validate_login'

  get 'admin', to: "dashboard#index"
  get 'login', to: "access#login"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'dashboard/index'
  get 'css_sample/index'
  get 'css_sample/home'

  resources :deduction_details
  resources :deductions
  resources :salaries
  resources :leave_details
  resources :leaves
  resources :day_types
  resources :attendances
  resources :departments
  resources :admin_users
  resources :salary_types
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  belongs_to :day_type_name, foreign_key: "day_type", class_name: "DayType"

  scope :attendance_by_date, -> (id) {where(day_type: id)}
  
end

app/models/day_type.rb
class DayType < ApplicationRecord
  belongs_to :employee, foreign_key: 'user_id'
  has_many :attendances, foreign_key: 'day_type'
  
  scope :sorted, -> {order(id: :desc)}

  private
    
end

app/models/deduction.rb
class Deduction < ApplicationRecord
  belongs_to :deduction_detail, foreign_key: "deduction_id"
  belongs_to :salary
end

app/models/deduction_detail.rb
class DeductionDetail < ApplicationRecord
  has_many :deduction
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :employee, foreign_key: 'manager'
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one_attached :image
  belongs_to :salary_type
  belongs_to :department
  has_many :departments
  has_many :attendances
  has_many :day_types
  has_many :leaves
  has_many :salaries
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :employee
  belongs_to :leave_detail, foreign_key: "leave_details_id"
end

app/models/leave_detail.rb
class LeaveDetail < ApplicationRecord
  has_many :leaves, class_name: :Leave, foreign_key: "leave_details_id"
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee
  has_many :deduction
end

app/models/salary_type.rb
class SalaryType < ApplicationRecord
  has_many :employees
end

app/controllers/salary_types_controller.rb
class SalaryTypesController < ApplicationController
  before_action :set_salary_type, only: [:show, :edit, :update, :destroy]

  # GET /salary_types
  # GET /salary_types.json
  def index
    @salary_types = SalaryType.all
  end

  # GET /salary_types/1
  # GET /salary_types/1.json
  def show
  end

  # GET /salary_types/new
  def new
    @salary_type = SalaryType.new
  end

  # GET /salary_types/1/edit
  def edit
  end

  # POST /salary_types
  # POST /salary_types.json
  def create
    @salary_type = SalaryType.new(salary_type_params)

    respond_to do |format|
      if @salary_type.save
        format.html { redirect_to @salary_type, notice: 'Salary type was successfully created.' }
        format.json { render :show, status: :created, location: @salary_type }
      else
        format.html { render :new }
        format.json { render json: @salary_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salary_types/1
  # PATCH/PUT /salary_types/1.json
  def update
    respond_to do |format|
      if @salary_type.update(salary_type_params)
        format.html { redirect_to @salary_type, notice: 'Salary type was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary_type }
      else
        format.html { render :edit }
        format.json { render json: @salary_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_types/1
  # DELETE /salary_types/1.json
  def destroy
    @salary_type.destroy
    respond_to do |format|
      format.html { redirect_to salary_types_url, notice: 'Salary type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary_type
      @salary_type = SalaryType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_type_params
      params.require(:salary_type).permit(:name, :hourly_rate, :daily_rate, :overtime_rate)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/css_sample_helper.rb
module CssSampleHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/day_types_helper.rb
module DayTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/salary_types_helper.rb
module SalaryTypesHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/salary_types/_form.html.erb
<div class="jumbotron form-center">
<%= form_with(model: salary_type, local: true) do |form| %>
  <% if salary_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salary_type.errors.count, "error") %> prohibited this salary_type from being saved:</h2>

      <ul>
      <% salary_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hourly_rate %>
    <%= form.text_field :hourly_rate %>
  </div>

  <div class="field">
    <%= form.label :daily_rate %>
    <%= form.text_field :daily_rate %>
  </div>

  <div class="field">
    <%= form.label :overtime_rate %>
    <%= form.text_field :overtime_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salary_types/edit.html.erb
<h1>Editing Salary Type</h1>

<%= render 'form', salary_type: @salary_type %>

<%= link_to 'Show', @salary_type %> |
<%= link_to 'Back', salary_types_path %>

app/views/salary_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salary Types</h1>
<hr>
<div class="jumbotron">
<table class="model-information">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hourly rate</th>
      <th>Daily rate</th>
      <th>Overtime rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salary_types.each do |salary_type| %>
      <tr>
        <td><%= salary_type.name %></td>
        <td><%= salary_type.hourly_rate %></td>
        <td><%= salary_type.daily_rate %></td>
        <td><%= salary_type.overtime_rate %></td>
        <td><%= link_to 'Show', salary_type %></td>
        <td><%= link_to 'Edit', edit_salary_type_path(salary_type) %></td>
        <td><%= link_to 'Destroy', salary_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary Type', new_salary_type_path, class: "btn btn-primary margin-normal"  %>

app/views/salary_types/new.html.erb
<h1>New Salary Type</h1>

<%= render 'form', salary_type: @salary_type %>

<%= link_to 'Back', salary_types_path %>

app/views/salary_types/show.html.erb
<div class="show-details">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salary_type.name %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @salary_type.hourly_rate %>
</p>

<p>
  <strong>Daily rate:</strong>
  <%= @salary_type.daily_rate %>
</p>

<p>
  <strong>Overtime rate:</strong>
  <%= @salary_type.overtime_rate %>
</p>

<%= link_to 'Edit', edit_salary_type_path(@salary_type) %> |
<%= link_to 'Back', salary_types_path %>