config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  root 'summary#index' 


  get 'home/login'
  get 'home/index'
  get 'home/home'
  get 'home/clear_employee'
  post 'home/time_in_user'
  post 'home/validate_login'

  get 'admin', to: "dashboard#index"
  get 'login', to: "access#login"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'dashboard/index'
  get 'css_sample/index'
  get 'css_sample/home'

  resources :deduction_details
  resources :deductions
  resources :salaries
  resources :leave_details
  resources :leaves
  resources :day_types
  resources :attendances
  resources :departments
  resources :admin_users
  resources :salary_types
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  belongs_to :day_type_name, foreign_key: "day_type", class_name: "DayType"

  scope :attendance_by_date, -> (id) {where(day_type: id)}
  
end

app/models/day_type.rb
class DayType < ApplicationRecord
  belongs_to :employee, foreign_key: 'user_id'
  has_many :attendances, foreign_key: 'day_type'
  
  scope :sorted, -> {order(id: :desc)}

  private
    
end

app/models/deduction.rb
class Deduction < ApplicationRecord
  belongs_to :deduction_detail, foreign_key: "deduction_id"
  belongs_to :salary
end

app/models/deduction_detail.rb
class DeductionDetail < ApplicationRecord
  has_many :deduction
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :employee, foreign_key: 'manager'
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one_attached :image
  belongs_to :salary_type
  belongs_to :department
  has_many :departments
  has_many :attendances
  has_many :day_types
  has_many :leaves
  has_many :salaries
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :employee
  belongs_to :leave_detail, foreign_key: "leave_details_id"
end

app/models/leave_detail.rb
class LeaveDetail < ApplicationRecord
  has_many :leaves, class_name: :Leave, foreign_key: "leave_details_id"
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee
  has_many :deduction
end

app/models/salary_type.rb
class SalaryType < ApplicationRecord
  has_many :employees
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(salary_params)

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: 'Salary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:employee_id, :start_date, :end_date)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/css_sample_helper.rb
module CssSampleHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/day_types_helper.rb
module DayTypesHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/salaries/_form.html.erb
<div class="jumbotron form-center">
<%= form_with(model: salary, local: true) do |form| %>
  <% if salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% salary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing Salary</h1>

<%= render 'form', salary: @salary %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>

app/views/salaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salaries</h1>
<hr>
<div class="jumbotron">
<table class="model-information">
  <thead>
    <tr>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.employee_id %></td>
        <td><%= salary.start_date %></td>
        <td><%= salary.end_date %></td>
        <td><%= link_to 'Show', salary %></td>
        <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary', new_salary_path, class: "btn btn-primary margin-normal"  %>

app/views/salaries/new.html.erb
<h1>New Salary</h1>

<%= render 'form', salary: @salary %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<div class="show-details">
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @salary.employee_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @salary.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @salary.end_date %>
</p>

<%= link_to 'Edit', edit_salary_path(@salary) %> |
<%= link_to 'Back', salaries_path %>