config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'
  root 'summary#index' 


  get 'home/login'
  get 'home/index'
  get 'home/home'
  get 'home/clear_employee'
  post 'home/time_in_user'
  post 'home/validate_login'

  get 'admin', to: "dashboard#index"
  get 'login', to: "access#login"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'dashboard/index'
  get 'css_sample/index'
  get 'css_sample/home'

  resources :deduction_details
  resources :deductions
  resources :salaries
  resources :leave_details
  resources :leaves
  resources :day_types
  resources :attendances
  resources :departments
  resources :admin_users
  resources :salary_types
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  belongs_to :day_type_name, foreign_key: "day_type", class_name: "DayType"

  scope :attendance_by_date, -> (id) {where(day_type: id)}
  
end

app/models/day_type.rb
class DayType < ApplicationRecord
  belongs_to :employee, foreign_key: 'user_id'
  has_many :attendances, foreign_key: 'day_type'
  
  scope :sorted, -> {order(id: :desc)}

  private
    
end

app/models/deduction.rb
class Deduction < ApplicationRecord
  belongs_to :deduction_detail, foreign_key: "deduction_id"
  belongs_to :salary
end

app/models/deduction_detail.rb
class DeductionDetail < ApplicationRecord
  has_many :deduction
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :employee, foreign_key: 'manager'
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one_attached :image
  belongs_to :salary_type
  belongs_to :department
  has_many :departments
  has_many :attendances
  has_many :day_types
  has_many :leaves
  has_many :salaries
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :employee
  belongs_to :leave_detail, foreign_key: "leave_details_id"
end

app/models/leave_detail.rb
class LeaveDetail < ApplicationRecord
  has_many :leaves, class_name: :Leave, foreign_key: "leave_details_id"
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee
  has_many :deduction
end

app/models/salary_type.rb
class SalaryType < ApplicationRecord
  has_many :employees
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin_users
  # GET /admin_users.json
  def index
    @admin_users = AdminUser.all
  end

  # GET /admin_users/1
  # GET /admin_users/1.json
  def show
  end

  # GET /admin_users/new
  def new
    @admin_user = AdminUser.new
  end

  # GET /admin_users/1/edit
  def edit
  end

  # POST /admin_users
  # POST /admin_users.json
  def create
    @admin_user = AdminUser.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_users/1
  # PATCH/PUT /admin_users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_users/1
  # DELETE /admin_users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'Admin user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = AdminUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:email, :password, :password_confirmation, :name, :contact_no)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/css_sample_helper.rb
module CssSampleHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/day_types_helper.rb
module DayTypesHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/admin_users/_form.html.erb
<div class="jumbotron form-center">
<%= form_with(model: admin_user, local: true) do |form| %>
  
  <% if admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact_no %>
    <%= form.text_field :contact_no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Users</h1>
<hr>
<div class="jumbotron">
  <table class="model-information">
    <thead>
      <tr>
        <th>Email</th>
        <th>Password digest</th>
        <th>Name</th>
        <th>Contact no</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_users.each do |admin_user| %>
        <tr>
          <td><%= admin_user.email %></td>
          <td><%= admin_user.password_digest %></td>
          <td><%= admin_user.name %></td>
          <td><%= admin_user.contact_no %></td>
          <td><%= link_to 'Show', admin_user %></td>
          <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
          <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Admin User', new_admin_user_path, class: "btn btn-primary margin-normal"  %>
  </div>

app/views/admin_users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin_users/show.html.erb
<div class="show-details">
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin_user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @admin_user.password_digest %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_user.name %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @admin_user.contact_no %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>